---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-appserver
  labels:
    app: {{ .Values.name }}-appserver
    tier: {{ .Values.tier.appserver }}
spec:
  type: {{ .Values.service.appserver }}
  ports:
  - port: {{ .Values.service.containerPort.appserver }}
  selector:
    app: {{ .Values.name }}-appserver
    tier: {{ .Values.tier.appserver }}

